//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utilities {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplatesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplatesResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utilities.EmailTemplatesResource", typeof(EmailTemplatesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAdjuntarFacturaRecepcion {
            get {
                return ResourceManager.GetString("EmailAdjuntarFacturaRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionAnularRecepcion {
            get {
                return ResourceManager.GetString("EmailAprobacionAnularRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGerenteArea {
            get {
                return ResourceManager.GetString("EmailAprobacionGerenteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGerenteAreaFueraPresupuesto {
            get {
                return ResourceManager.GetString("EmailAprobacionGerenteAreaFueraPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGerenteAreaPago {
            get {
                return ResourceManager.GetString("EmailAprobacionGerenteAreaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGerenteGeneral {
            get {
                return ResourceManager.GetString("EmailAprobacionGerenteGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGerenteGeneralPago {
            get {
                return ResourceManager.GetString("EmailAprobacionGerenteGeneralPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionGestorCompra {
            get {
                return ResourceManager.GetString("EmailAprobacionGestorCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionJefeArea {
            get {
                return ResourceManager.GetString("EmailAprobacionJefeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionJefeCompra {
            get {
                return ResourceManager.GetString("EmailAprobacionJefeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionJefeInmediato {
            get {
                return ResourceManager.GetString("EmailAprobacionJefeInmediato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionJefeInmediatoMontoMayor {
            get {
                return ResourceManager.GetString("EmailAprobacionJefeInmediatoMontoMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionJefeInmediatoPago {
            get {
                return ResourceManager.GetString("EmailAprobacionJefeInmediatoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionRecepcion {
            get {
                return ResourceManager.GetString("EmailAprobacionRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionSubgerenteArea {
            get {
                return ResourceManager.GetString("EmailAprobacionSubgerenteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionSubgerenteAreaPago {
            get {
                return ResourceManager.GetString("EmailAprobacionSubgerenteAreaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionVicepresidenteFinanciero {
            get {
                return ResourceManager.GetString("EmailAprobacionVicepresidenteFinanciero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionVicepresidenteFinancieroFueraPresupuesto {
            get {
                return ResourceManager.GetString("EmailAprobacionVicepresidenteFinancieroFueraPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailAprobacionVicepresidenteFinancieroPago {
            get {
                return ResourceManager.GetString("EmailAprobacionVicepresidenteFinancieroPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailContabilizarPago {
            get {
                return ResourceManager.GetString("EmailContabilizarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailContabilizarRecepcion {
            get {
                return ResourceManager.GetString("EmailContabilizarRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailCorreccionJefeCompraProductoOtro {
            get {
                return ResourceManager.GetString("EmailCorreccionJefeCompraProductoOtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailDevolucionContabilidadSolicitantePago {
            get {
                return ResourceManager.GetString("EmailDevolucionContabilidadSolicitantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailDevolucionSolicitante {
            get {
                return ResourceManager.GetString("EmailDevolucionSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailDevolucionSolicitantePago {
            get {
                return ResourceManager.GetString("EmailDevolucionSolicitantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailEnviarOrdenAlProveedor {
            get {
                return ResourceManager.GetString("EmailEnviarOrdenAlProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailEnviarOrdenAlSolicitante {
            get {
                return ResourceManager.GetString("EmailEnviarOrdenAlSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailEscalamientoAnteriorResponsable {
            get {
                return ResourceManager.GetString("EmailEscalamientoAnteriorResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailEscalamientoNuevoResponsable {
            get {
                return ResourceManager.GetString("EmailEscalamientoNuevoResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailPrevioEscalamiento {
            get {
                return ResourceManager.GetString("EmailPrevioEscalamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRecepcionBienServicio {
            get {
                return ResourceManager.GetString("EmailRecepcionBienServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRecepcionNegada {
            get {
                return ResourceManager.GetString("EmailRecepcionNegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRechazo {
            get {
                return ResourceManager.GetString("EmailRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRechazoContabilizacionPago {
            get {
                return ResourceManager.GetString("EmailRechazoContabilizacionPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRechazoPago {
            get {
                return ResourceManager.GetString("EmailRechazoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailRecordatorioEscalamiento {
            get {
                return ResourceManager.GetString("EmailRecordatorioEscalamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width:100% !important; background-color:#fafafa !important; margin:0 !important; padding:0 !important;&quot;&gt;
        ///        &lt;table style=&quot;height:100% !important; width:100% !important; background-color:#fafafa; margin:0; padding:0;&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td align=&quot;center&quot;&gt;
        ///                        &lt;table style=&quot;background-color:#ffffff; border:1px solid #dddd [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EmailVerificarPresupuesto {
            get {
                return ResourceManager.GetString("EmailVerificarPresupuesto", resourceCulture);
            }
        }
    }
}
