using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Common.Utilities
{
    public enum EnumEstado
    {
        ACTIVO = 1,
        INACTIVO = 2
    }

    public enum EnumTiempoColor
    {
        VERDE = 1,
        AMARILLO = 2,
        ROJO = 3
    }

    public enum EnumTipoTarea
    {
        CREACION_SOLICITUD = 0,
        APROBACION_JEFE_INMEDIATO = 1,
        APROBACION_GESTOR_COMPRA = 2,
        APROBACION_JEFE_COMPRA_PRODUCTO_OTRO = 3,
        APROBACION_JEFE_COMPRA = 4,
        VERIFICACION_PRESUPUESTO = 5,
        RETORNO_A_JEFE_INMEDIATO = 6,
        RECEPCION = 7,
        APROBACION_DESEMBOLSO = 8,
        APROBACION_ANULACION_RECEPCION = 9,
        ADJUNTAR_FACTURA = 10,
        CONTABILIZAR_RECEPCION = 11,
        DEVOLVER_A_SOLICITANTE = 12,
        DEVOLVER_A_GESTOR_COMPRA = 13,
        APROBACION_FUERA_PRESUPUESTO_GERENTE_AREA = 14,
        APROBACION_FUERA_PRESUPUESTO_VICEPRESIDENTE_FINANCIERO = 15,
        APROBACION_POR_MONTO_JEFE_AREA = 16,
        APROBACION_POR_MONTO_SUBGERENTE_AREA = 17,
        APROBACION_POR_MONTO_GERENTE_AREA = 18,
        APROBACION_POR_MONTO_VICEPRESIDENTE_FINANCIERO = 19,
        APROBACION_POR_MONTO_GERENTE_GENERAL = 20,
        ANULACION_RECEPCION = 21
    }

    public enum EnumTipoTareaPago
    {
        CREACION_SOLICITUD = 0,      
        DEVOLVER_A_SOLICITANTE_JEFE = 1,
        DEVOLVER_A_SOLICITANTE_CONTABILIDAD = 2,
        APROBACION_POR_MONTO_JEFE_AREA = 3,
        APROBACION_POR_MONTO_SUBGERENTE_AREA = 4,
        APROBACION_POR_MONTO_GERENTE_AREA = 5,
        APROBACION_POR_MONTO_VICEPRESIDENTE_FINANCIERO = 6,
        APROBACION_POR_MONTO_GERENTE_GENERAL = 7,
        CONTABILIZAR = 8,
        DEVOLVER_A_SOLICITANTE_JEFE_CONTABILIDAD = 9
    }

    public enum EnumRol
    {
        ADMIN_COMPRA_ANULACION_RECEPCION = 1,
        ADMIN_COMPRA_REPORTE_HISTORIAL_TAREAS = 2,
        ADMIN_COMPRA_REPORTE_SEGUIMIENTO_PROCESOS = 3,
        ADMIN_COMPRA_ROLES_GESTORES_COMPRA = 4,
        ADMIN_COMPRA_REASIGNACION_TAREAS = 5,
        ADMIN_COMPRA_DETENER_SOLICITUDES = 6,
        ADMIN_COMPRA_REASIGNACION_ORIGINADOR = 20,
        ADMIN_COMPRA_EMAILS_PENDIENTES = 21,

        ADMIN_ROLES_ADMINISTRATIVOS = 7,

        ADMIN_PAGO_IMPUESTOS = 11,
        //ADMIN_PAGO_PARAMETROS = 12,
        ADMIN_PAGO_TIPOS_PAGO = 13,
        ADMIN_PAGO_REPORTE_HISTORIAL_TAREAS = 14,
        ADMIN_PAGO_REPORTE_SEGUIMIENTO_PROCESOS = 15,
        ADMIN_PAGO_REASIGNACION_TAREAS = 16,
        //ADMIN_PAGO_REPORTE_DATA_WAREHOUSE = 17,
        //ADMIN_PAGO_CONFIG_FACTURA_ELECTRONICA = 18,

        PROC_COMPRA_VERIFICAR_PRESUPUESTO = 8,
        PROC_COMPRA_ADJUNTAR_FACTURA = 9,
        PROC_COMPRA_CONTABILIZAR_RECEPCION = 10,

        PROC_PAGO_CONTABILIZAR = 19
    }

    public enum EnumCatalogoTipoDocumento
    {
        FACTURA = 1,
        NOTA_DE_CREDITO = 4,
        NOTA_DE_DEBITO = 5,
        GUIA_DE_REMISION = 6,
        COMPROBANTE_DE_RETENCION = 7
    }
}
